// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1z3F4DDPxx20-iQ9cnzGIbWjxzQkKTg',
    appId: '1:368704473385:web:16fab4907a30fd20134f38',
    messagingSenderId: '368704473385',
    projectId: 'overdoseshieldwa',
    authDomain: 'overdoseshieldwa.firebaseapp.com',
    storageBucket: 'overdoseshieldwa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1z3F4DDPxx20-iQ9cnzGIbWjxzQkKTg',
    appId: '1:368704473385:android:16fab4907a30fd20134f38',
    messagingSenderId: '368704473385',
    projectId: 'overdoseshieldwa',
    storageBucket: 'overdoseshieldwa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ1z3F4DDPxx20-iQ9cnzGIbWjxzQkKTg',
    appId: '1:368704473385:ios:16fab4907a30fd20134f38',
    messagingSenderId: '368704473385',
    projectId: 'overdoseshieldwa',
    storageBucket: 'overdoseshieldwa.firebasestorage.app',
    iosBundleId: 'com.overdoseshield.narcan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ1z3F4DDPxx20-iQ9cnzGIbWjxzQkKTg',
    appId: '1:368704473385:ios:16fab4907a30fd20134f38',
    messagingSenderId: '368704473385',
    projectId: 'overdoseshieldwa',
    storageBucket: 'overdoseshieldwa.firebasestorage.app',
    iosBundleId: 'com.overdoseshield.narcan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ1z3F4DDPxx20-iQ9cnzGIbWjxzQkKTg',
    appId: '1:368704473385:web:16fab4907a30fd20134f38',
    messagingSenderId: '368704473385',
    projectId: 'overdoseshieldwa',
    authDomain: 'overdoseshieldwa.firebaseapp.com',
    storageBucket: 'overdoseshieldwa.firebasestorage.app',
  );
}
